masterclasses = {
    "masterclass_1": {
        "id": "masterclass_1",
        "title": "Футболка с нуля",
        "description": "Учимся шить базовую футболку с нуля, выбираем ткань и фурнитуру.",
        "photo_url": "https://picsum.photos/200/300?random=1",
        "link": "https://example.com/masterclass1",
        "category": "Рубашки и футболки ",
    },
    "masterclass_2": {
        "id": "masterclass_2",
        "title": "Юбка-солнце",
        "description": "Пошаговое руководство по созданию юбки-солнце на лето.",
        "photo_url": "https://picsum.photos/200/300?random=2",
        "link": "https://example.com/masterclass2",
        "category": "Юбки",
    },
    "masterclass_3": {
        "id": "masterclass_3",
        "title": "Рубашка на пуговицах",
        "description": "Подробный разбор кроя и сборка рубашки с воротником и манжетами.",
        "photo_url": "https://picsum.photos/200/300?random=3",
        "link": "https://example.com/masterclass3",
        "category": "Рубашки и футболки",
    },
    "masterclass_4": {
        "id": "masterclass_4",
        "title": "Платье с открытыми плечами",
        "description": "Создаем лёгкое платье с оригинальными рукавами-воланами.",
        "photo_url": "https://picsum.photos/200/300?random=4",
        "link": "https://example.com/masterclass4",
        "category": "Платья",
    },
    "masterclass_5": {
        "id": "masterclass_5",
        "title": "Брюки с высокой талией",
        "description": "Техника пошива удобных и стильных брюк с высокой посадкой.",
        "photo_url": "https://picsum.photos/200/300?random=5",
        "link": "https://example.com/masterclass5",
        "category": "Брюки и шорты",
    },
    "masterclass_6": {
        "id": "masterclass_6",
        "title": "Классический пиджак",
        "description": "Основы кроя и сборки пиджака для начинающих портных.",
        "photo_url": "https://picsum.photos/200/300?random=6",
        "link": "https://example.com/masterclass6",
        "category": "Верхняя одежда",
    },
    "masterclass_7": {
        "id": "masterclass_7",
        "title": "Худи с капюшоном",
        "description": "Удобный спортивный стиль — шьем худи своими руками.",
        "photo_url": "https://picsum.photos/200/300?random=7",
        "link": "https://example.com/masterclass7",
        "category": "Верхняя одежда",
    },
    "masterclass_8": {
        "id": "masterclass_8",
        "title": "Жилет без подкладки 🔥",
        "description": "Легкий жилет для весны и осени — делаем шаг за шагом.",
        "photo_url": "https://picsum.photos/200/300?random=8",
        "link": "https://example.com/masterclass8",
        "category": "Верхняя одежда",
    },
    "masterclass_9": {
        "id": "masterclass_9",
        "title": "Мужская рубашка",
        "description": "Тонкости мужского кроя и правильный выбор тканей.",
        "photo_url": "https://picsum.photos/200/300?random=9",
        "link": "https://example.com/masterclass9",
        "category": "Рубашки и футболки",
    },
    "masterclass_10": {
        "id": "masterclass_10",
        "title": "Пижама с брюками",
        "description": "Комфортная домашняя одежда — простой пошив пижамы.",
        "photo_url": "https://picsum.photos/200/300?random=10",
        "link": "https://example.com/masterclass10",
        "category": "Домашняя одежда",
    },
    "masterclass_11": {
        "id": "masterclass_11",
        "title": "Легкий плащ",
        "description": "Стильный плащ без подкладки для переменчивой погоды.",
        "photo_url": "https://picsum.photos/200/300?random=11",
        "link": "https://example.com/masterclass11",
        "category": "Верхняя одежда",
    },
    "masterclass_12": {
        "id": "masterclass_12",
        "title": "Детский сарафан 🔥",
        "description": "Яркий и удобный сарафан для девочек, от идеи до готового изделия.",
        "photo_url": "https://picsum.photos/200/300?random=12",
        "link": "https://example.com/masterclass12",
        "category": "Детская одежда",
    },
    "masterclass_13": {
        "id": "masterclass_13",
        "title": "Платье-футляр",
        "description": "Советы по работе с трикотажем и пошив элегантного платья.",
        "photo_url": "https://picsum.photos/200/300?random=13",
        "link": "https://example.com/masterclass13",
        "category": "Платья",
    },
    "masterclass_14": {
        "id": "masterclass_14",
        "title": "Женский комбинезон",
        "description": "Удобный и стильный комбинезон своими руками.",
        "photo_url": "https://picsum.photos/200/300?random=14",
        "link": "https://example.com/masterclass14",
        "category": "Комбинезоны",
    },
    "masterclass_15": {
        "id": "masterclass_15",
        "title": "Куртка с капюшоном",
        "description": "Пошаговое создание теплой и практичной куртки.",
        "photo_url": "https://picsum.photos/200/300?random=15",
        "link": "https://example.com/masterclass15",
        "category": "Верхняя одежда",
    },
    "masterclass_16": {
        "id": "masterclass_16",
        "title": "Юбка-карандаш",
        "description": "Классика офисного стиля — учимся шить юбку-карандаш.",
        "photo_url": "https://picsum.photos/200/300?random=16",
        "link": "https://example.com/masterclass16",
        "category": "Юбки",
    },
    "masterclass_17": {
        "id": "masterclass_17",
        "title": "Летние шорты",
        "description": "Летние шорты своими руками — быстро и просто.",
        "photo_url": "https://picsum.photos/200/300?random=17",
        "link": "https://example.com/masterclass17",
        "category": "Брюки и шорты",
    },
    "masterclass_18": {
        "id": "masterclass_18",
        "title": "Свитер из трикотажа",
        "description": "Учимся работать с трикотажем, чтобы создать уютный свитер.",
        "photo_url": "https://picsum.photos/200/300?random=18",
        "link": "https://example.com/masterclass18",
        "category": "Верхняя одежда",
    },
    "masterclass_19": {
        "id": "masterclass_19",
        "title": "Платье с запахом 🆕",
        "description": "Пошив модного платья с запахом для любого сезона.",
        "photo_url": "https://picsum.photos/200/300?random=19",
        "link": "https://example.com/masterclass19",
        "category": "Платья",
    },
    "masterclass_20": {
        "id": "masterclass_20",
        "title": "Жилетка с капюшоном 🆕",
        "description": "Легкая жилетка с капюшоном для повседневной носки.",
        "photo_url": "https://picsum.photos/200/300?random=20",
        "link": "https://example.com/masterclass20",
        "category": "Верхняя одежда",
    },
}

videocourses = {
    "videocourse_1": {
        "id": "videocourse_1",
        "title": "Основы шитья",
        "description": "Пошаговое введение в шитье: выбор материалов, инструменты, базовые техники.",
        "photo_url": "https://picsum.photos/200/300?random=1",
        "link": "https://example.com/videocourse1",
        "category": "Основы",
    },
    "videocourse_2": {
        "id": "videocourse_2",
        "title": "Футболка своими руками",
        "description": "Учимся шить базовую футболку из трикотажа с нуля.",
        "photo_url": "https://picsum.photos/200/300?random=2",
        "link": "https://example.com/videocourse2",
        "category": "Рубашки и футболки",
    },
    "videocourse_3": {
        "id": "videocourse_3",
        "title": "Юбка-солнце за 3 урока",
        "description": "Как быстро и качественно сшить юбку-солнце для летнего гардероба.",
        "photo_url": "https://picsum.photos/200/300?random=3",
        "link": "https://example.com/videocourse3",
        "category": "Юбки",
    },
    "videocourse_4": {
        "id": "videocourse_4",
        "title": "Рубашка с воротником",
        "description": "Разбираем этапы пошива классической рубашки с воротником и манжетами.",
        "photo_url": "https://picsum.photos/200/300?random=4",
        "link": "https://example.com/videocourse4",
        "category": "Рубашки и футболки",
    },
    "videocourse_5": {
        "id": "videocourse_5",
        "title": "Летнее платье с воланами",
        "description": "Создаем легкое платье с красивыми воланами на рукавах.",
        "photo_url": "https://picsum.photos/200/300?random=5",
        "link": "https://example.com/videocourse5",
        "category": "Платья",
    },
    "videocourse_6": {
        "id": "videocourse_6",
        "title": "Брюки с высокой талией",
        "description": "Как сшить стильные брюки с высокой посадкой и карманами.",
        "photo_url": "https://picsum.photos/200/300?random=6",
        "link": "https://example.com/videocourse6",
        "category": "Брюки и шорты",
    },
    "videocourse_7": {
        "id": "videocourse_7",
        "title": "Пиджак своими руками",
        "description": "От выбора ткани до финальной обработки — пошив классического пиджака.",
        "photo_url": "https://picsum.photos/200/300?random=7",
        "link": "https://example.com/videocourse7",
        "category": "Верхняя одежда",
    },
    "videocourse_8": {
        "id": "videocourse_8",
        "title": "Уютное худи",
        "description": "Учимся шить удобное худи из толстовочной ткани для повседневной носки.",
        "photo_url": "https://picsum.photos/200/300?random=8",
        "link": "https://example.com/videocourse8",
        "category": "Верхняя одежда",
    },
    "videocourse_9": {
        "id": "videocourse_9",
        "title": "Жилет без подкладки",
        "description": "Легкий жилет — отличное дополнение к образу в межсезонье.",
        "photo_url": "https://picsum.photos/200/300?random=9",
        "link": "https://example.com/videocourse9",
        "category": "Верхняя одежда",
    },
    "videocourse_10": {
        "id": "videocourse_10",
        "title": "Мужская рубашка",
        "description": "Пошив классической мужской рубашки с детальным разбором этапов.",
        "photo_url": "https://picsum.photos/200/300?random=10",
        "link": "https://example.com/videocourse10",
        "category": "Рубашки и футболки",
    },
    "videocourse_11": {
        "id": "videocourse_11",
        "title": "Домашняя пижама 🔥",
        "description": "Пошив удобной пижамы — брюки и рубашка своими руками.",
        "photo_url": "https://picsum.photos/200/300?random=11",
        "link": "https://example.com/videocourse11",
        "category": "Домашняя одежда",
    },
    "videocourse_12": {
        "id": "videocourse_12",
        "title": "Весенний плащ",
        "description": "Легкий плащ без подкладки — пошаговое создание.",
        "photo_url": "https://picsum.photos/200/300?random=12",
        "link": "https://example.com/videocourse12",
        "category": "Верхняя одежда",
    },
    "videocourse_13": {
        "id": "videocourse_13",
        "title": "Детский сарафан",
        "description": "Яркий и удобный сарафан для девочек с простым кроем.",
        "photo_url": "https://picsum.photos/200/300?random=13",
        "link": "https://example.com/videocourse13",
        "category": "Детская одежда",
    },
    "videocourse_14": {
        "id": "videocourse_14",
        "title": "Платье-футляр 🔥",
        "description": "Советы и пошив облегающего платья из трикотажной ткани.",
        "photo_url": "https://picsum.photos/200/300?random=14",
        "link": "https://example.com/videocourse14",
        "category": "Платья",
    },
    "videocourse_15": {
        "id": "videocourse_15",
        "title": "Женский комбинезон",
        "description": "Стильный комбинезон с поясом — шьем своими руками.",
        "photo_url": "https://picsum.photos/200/300?random=15",
        "link": "https://example.com/videocourse15",
        "category": "Комбинезоны",
    },
    "videocourse_16": {
        "id": "videocourse_16",
        "title": "Теплая куртка",
        "description": "Пошаговое руководство по созданию теплой куртки.",
        "photo_url": "https://picsum.photos/200/300?random=16",
        "link": "https://example.com/videocourse16",
        "category": "Верхняя одежда",
    },
    "videocourse_17": {
        "id": "videocourse_17",
        "title": "Юбка-карандаш",
        "description": "Как сшить классическую юбку-карандаш для офиса и вечера.",
        "photo_url": "https://picsum.photos/200/300?random=17",
        "link": "https://example.com/videocourse17",
        "category": "Юбки",
    },
    "videocourse_18": {
        "id": "videocourse_18",
        "title": "Летние шорты",
        "description": "Быстрый и легкий пошив летних шорт с карманами.",
        "photo_url": "https://picsum.photos/200/300?random=18",
        "link": "https://example.com/videocourse18",
        "category": "Брюки и шорты",
    },
    "videocourse_19": {
        "id": "videocourse_19",
        "title": "Свитер из трикотажа 🆕",
        "description": "Пошив уютного свитера с рукавами реглан из трикотажа.",
        "photo_url": "https://picsum.photos/200/300?random=19",
        "link": "https://example.com/videocourse19",
        "category": "Верхняя одежда",
    },
    "videocourse_20": {
        "id": "videocourse_20",
        "title": "Платье с запахом 🆕",
        "description": "Модный пошив платья с запахом для любого сезона.",
        "photo_url": "https://picsum.photos/200/300?random=20",
        "link": "https://example.com/videocourse20",
        "category": "Платья",
    },
}

patterns = {
    "pattern_1": {
        "id": "pattern_1",
        "title": "Базовая футболка",
        "description": "Простая выкройка для пошива футболки из трикотажа.",
        "photo_url": "https://picsum.photos/200/300?random=1",
        "link": "https://example.com/pattern1",
        "category": "Рубашки и футболки",
    },
    "pattern_2": {
        "id": "pattern_2",
        "title": "Юбка-солнце",
        "description": "Классическая выкройка для юбки-солнце любого размера.",
        "photo_url": "https://picsum.photos/200/300?random=2",
        "link": "https://example.com/pattern2",
        "category": "Юбки",
    },
    "pattern_3": {
        "id": "pattern_3",
        "title": "Классическая рубашка",
        "description": "Детальная выкройка для рубашки с воротником и манжетами.",
        "photo_url": "https://picsum.photos/200/300?random=3",
        "link": "https://example.com/pattern3",
        "category": "Рубашки и футболки",
    },
    "pattern_4": {
        "id": "pattern_4",
        "title": "Летнее платье с открытыми плечами",
        "description": "Легкая выкройка для женственного платья с воланами.",
        "photo_url": "https://picsum.photos/200/300?random=4",
        "link": "https://example.com/pattern4",
        "category": "Платья",
    },
    "pattern_5": {
        "id": "pattern_5",
        "title": "Брюки с высокой талией",
        "description": "Удобная выкройка для брюк с высокой посадкой и карманами.",
        "photo_url": "https://picsum.photos/200/300?random=5",
        "link": "https://example.com/pattern5",
        "category": "Брюки и шорты",
    },
    "pattern_6": {
        "id": "pattern_6",
        "title": "Пиджак",
        "description": "Подробная выкройка для классического пиджака с подкладкой.",
        "photo_url": "https://picsum.photos/200/300?random=6",
        "link": "https://example.com/pattern6",
        "category": "Верхняя одежда",
    },
    "pattern_7": {
        "id": "pattern_7",
        "title": "Худи с капюшоном",
        "description": "Универсальная выкройка для удобного худи из толстовочной ткани.",
        "photo_url": "https://picsum.photos/200/300?random=7",
        "link": "https://example.com/pattern7",
        "category": "Верхняя одежда",
    },
    "pattern_8": {
        "id": "pattern_8",
        "title": "Жилет без подкладки",
        "description": "Легкая выкройка жилета для межсезонья.",
        "photo_url": "https://picsum.photos/200/300?random=8",
        "link": "https://example.com/pattern8",
        "category": "Верхняя одежда",
    },
    "pattern_9": {
        "id": "pattern_9",
        "title": "Мужская рубашка",
        "description": "Классическая выкройка рубашки для мужчин с манжетами.",
        "photo_url": "https://picsum.photos/200/300?random=9",
        "link": "https://example.com/pattern9",
        "category": "Рубашки и футболки",
    },
    "pattern_10": {
        "id": "pattern_10",
        "title": "Пижама",
        "description": "Простая выкройка для домашнего костюма — брюки и рубашка.",
        "photo_url": "https://picsum.photos/200/300?random=10",
        "link": "https://example.com/pattern10",
        "category": "Домашняя одежда",
    },
    "pattern_11": {
        "id": "pattern_11",
        "title": "Легкий плащ",
        "description": "Выкройка для плаща без подкладки на весенний сезон.",
        "photo_url": "https://picsum.photos/200/300?random=11",
        "link": "https://example.com/pattern11",
        "category": "Верхняя одежда",
    },
    "pattern_12": {
        "id": "pattern_12",
        "title": "Детский сарафан",
        "description": "Простая и удобная выкройка для детского летнего сарафана.",
        "photo_url": "https://picsum.photos/200/300?random=12",
        "link": "https://example.com/pattern12",
        "category": "Детская одежда",
    },
    "pattern_13": {
        "id": "pattern_13",
        "title": "Платье-футляр из трикотажа",
        "description": "Выкройка для платья, облегающего фигуру с эластичной тканью.",
        "photo_url": "https://picsum.photos/200/300?random=13",
        "link": "https://example.com/pattern13",
        "category": "Платья",
    },
    "pattern_14": {
        "id": "pattern_14",
        "title": "Женский комбинезон",
        "description": "Стильная выкройка комбинезона с длинными брюками и поясом.",
        "photo_url": "https://picsum.photos/200/300?random=14",
        "link": "https://example.com/pattern14",
        "category": "Комбинезоны",
    },
    "pattern_15": {
        "id": "pattern_15",
        "title": "Куртка с капюшоном",
        "description": "Пошаговая выкройка для теплой куртки с удобным капюшоном.",
        "photo_url": "https://picsum.photos/200/300?random=15",
        "link": "https://example.com/pattern15",
        "category": "Верхняя одежда",
    },
    "pattern_16": {
        "id": "pattern_16",
        "title": "Юбка-карандаш 🔥",
        "description": "Классическая выкройка юбки, подходящая для офиса и вечерних выходов.",
        "photo_url": "https://picsum.photos/200/300?random=16",
        "link": "https://example.com/pattern16",
        "category": "Юбки",
    },
    "pattern_17": {
        "id": "pattern_17",
        "title": "Летние шорты 🔥",
        "description": "Удобная выкройка шорт с карманами и поясом на резинке.",
        "photo_url": "https://picsum.photos/200/300?random=17",
        "link": "https://example.com/pattern17",
        "category": "Брюки и шорты",
    },
    "pattern_18": {
        "id": "pattern_18",
        "title": "Свитер из трикотажа",
        "description": "Выкройка уютного свитера с рукавами реглан для начинающих.",
        "photo_url": "https://picsum.photos/200/300?random=18",
        "link": "https://example.com/pattern18",
        "category": "Верхняя одежда",
    },
    "pattern_19": {
        "id": "pattern_19",
        "title": "Платье с запахом",
        "description": "Модная выкройка платья с запахом, подходящего для разных сезонов.",
        "photo_url": "https://picsum.photos/200/300?random=19",
        "link": "https://example.com/pattern19",
        "category": "Платья",
    },
    "pattern_20": {
        "id": "pattern_20",
        "title": "Жилет с капюшоном 🆕",
        "description": "Легкая выкройка жилета с капюшоном для повседневной носки.",
        "photo_url": "https://picsum.photos/200/300?random=20",
        "link": "https://example.com/pattern20",
        "category": "Верхняя одежда",
    },
}
